<a id='dialog_OK_A' href="#dialog_OK" data-rel="dialog" data-transition="pop" style='display:none;'></a>
<div data-role="popup" id="dialog_OK" data-overlay-theme="b" data-theme="b" data-dismissible="false" class="dialog">
    <div data-role="header" data-theme="b">
        <h1 id='dialog_OK_head'></h1>
    </div>

    <div role="main" class="ui-content" style="text-align: center;">
        <div id="dialog_OK_body" style="margin-top: 1em; margin-bottom: 2em;"></div>
        <a href="#" data-role="button" data-rel="back" data-theme="b">OK</a>
    </div>
</div>
