<div data-role="popup" id="popupDialog" data-overlay-theme="b" data-theme="b" data-dismissible="false">
    <div data-role="header" data-theme="b">
        <h1>Read Instructions</h1>
    </div>

    <div role="main" class="ui-content" style="text-align: justify;">
        <p>Show slides and read the following text</p>
        <p>You are here today to participate in a study during which we will evaluate your current knowledge and skills regarding the management of patients with certain traumatic injuries.</p>
        <p>We will present you a total of four cases studies that will focus on dealing with specific traumatic injuries.</p>
        <p>For each case, I will ask you to fist describe:</p>
        <ol class="list">
            <li>The structures that you suspect might be injured</li>
            <li>The physical findings you would specifically look for</li>
            <li>The need for any additional studies and treatments</li>
            <li>The need for surgical intervention</li>
        </ol>
        <p>We will then transition to the patient being in the operating room and I will ask you to:</p>
        <ol class="list">
            <li>Describe how you would position and prep the patient for surgery</li>
            <li>Mark the key landmarks for your incision</li>
            <li>Perform the indicated procedure using the available instruments</li>
            <li>As you perform each procedure you will be asked to speak out loud, describing the steps as you perform them</li>
            <li>It is not necessary to rush through the procedure</li>
            <li>Once you start the procedure, I will try not to interrupt you</li>
            <li>Perform the procedure as you would with a real patient to allow accurate assessment of your surgical technique</li>
            <li>You will have 20 minutes to complete each indicated procedure. Time will begin at your first incision</li>
        </ol>
        
        <p><b>Do you have any questions?</b></p>
        <p>If you need any assistance with instruments or retractors please let us know</p>
        
        <a href="#" data-role="button" data-rel="back" data-theme="b">OK</a>
    </div>
</div>
